# -------------------------------------------------------------------
# Source des données (API, dépôt, corpus distant, etc.)
# -------------------------------------------------------------------
source:
  DTS_URL: "https://dots.chartes.psl.eu/demo/api/dts"
  TARGET_COLLECTION: ""  # Identifiant de la collection racine à explorer empty by default
  CUSTOM_SETTINGS_PATH: !!str ${CUSTOM_SETTINGS_PATH}
  ADDITIONAL_EXCLUDED_COLLECTIONS: []

# -------------------------------------------------------------------
# Configuration du moteur de recherche ES
# -------------------------------------------------------------------
config:
  ELASTICSEARCH_URL: "http://127.0.0.1:9200"
  DOCUMENT_INDEX: "dots_document"
  COLLECTION_INDEX: "dots_collection"
  SEARCH_RESULT_PER_PAGE: 200

# -------------------------------------------------------------------
# Paramètres d'indexation
# -------------------------------------------------------------------
indexing:
  MAX_CONCURRENT_REQUESTS: 5
  RESOURCE_WORKERS: 5
